import type { Metadata } from "next";
import Providers from "../components/Providers";
import { getCompany, getCompanies } from "./actions/companyActions";
import { getProjects } from "./actions/projectActions";
import "./globals.css";
import { useSession } from "next-auth/react";
import { auth } from "@/auth";
import { SecurityRole } from "@prisma/client";
import { emptyCompany, emptyProject } from "@/lib/schemas/defaultModels";

export const metadata: Metadata = {
  title: "Ace Project Services",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const user = session?.user;
  const companies =
    user?.securityRole === SecurityRole.ADMIN
      ? await getCompanies()
      : [await getCompany()];
  const projects = await getProjects();

  const initialCompanies = companies.length > 0 ? companies : [emptyCompany];
  const initialProjects = projects.length > 0 ? projects : [emptyProject];

  return (
    <html lang="en">
      <body>
        <Providers companies={initialCompanies} projects={initialProjects}>
          <main className="vertical-center">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
